Add Yoloface-8n
DefTruth/lite.ai.toolkit pull request #412
Opened 2024-07-09 07:43 UTC by wangzijian1010

大佬 你好 我从去年接触到深度学习部署之后 就有在一直关注你和你的知乎 这个lite.ai.toolkit更是一个非常优秀的项目 学习价值和实用价值都很高 也感谢大佬在知乎和github上无偿分享知识 刚接触的时候就想能有一天为大佬没精力维护的仓库能做点pull request 由于之前技术能力和水平以及平台问题 迟迟没有开始 本次我新增的是一个轻量级的人脸检测的算法yoloface8n 借鉴的是另外一位大佬的代码 [hpc203](https://github.com/hpc203) 也非常非常感谢hpc203大佬的分享 希望大佬们工作顺利 暴富暴富

2024-07-09 08:34 UTC, DefTruth commented
LGTM~ 如果你愿意，等我review并顺利合入这个PR后，我可以include你为这个repo的maintainer之一~

2024-07-09 09:05 UTC, DefTruth requested changes

2024-07-09 09:05 UTC, DefTruth commented on examples/lite/cv/test_lite_yolovfacev8.cpp
> +// 检测并绘制检测框
注释都修改成英文

2024-07-09 09:05 UTC, DefTruth commented on lite/ort/cv/yolofacev8.cpp
> +// 函数：保存 Ort::Value 数据到文本文件
同上，注释修改成英文~ 其余同理

2024-07-09 09:05 UTC, DefTruth commented on lite/ort/cv/yolofacev8.cpp
> +//    cv::Mat resize_mat = YoloFaceV8::normalize(mat_rs);
不需要的代码注释可以删除

2024-07-09 09:05 UTC, DefTruth commented on lite/ort/cv/yolofacev8.cpp
> +    // save_tensor_to_file(output_tensors[0],"/home/ai-test1/wangzijian/lite.ai.toolkit/TestExamples/out.txt");
删除不需要的代码注释以及临时的测试代码

2024-07-09 09:05 UTC, DefTruth commented on lite/types.h
> +      {
这里临时加的Bbox不规范，使用BoundingBoxType就可以了，可以参考yolo5face的实现

2024-07-09 09:06 UTC, DefTruth commented
@wangzijian1010 感谢您的贡献，还需要按照review的意见修改后才能合入哈~

2024-07-09 09:23 UTC, wangzijian1010 commented
> @wangzijian1010 感谢您的贡献，还需要按照review的意见修改后才能合入哈~
好的 感谢大佬百忙之中回复 我的代码规范性确实不是很好 感谢大佬提醒 我修改一下我的代码之后再次提交

2024-07-09 12:27 UTC, DefTruth commented
@wangzijian1010 同学，可以加我微信，后续有时间可以聊聊，微信和GitHub同名：DefTruth

2024-07-09 13:30 UTC, wangzijian1010 commented
> @wangzijian1010 同学，可以加我微信，后续有时间可以聊聊，微信和GitHub同名：DefTruth

马上就加 追星成功🥹🥹 大佬就是我刚刚更新了一版本的pull request那个人脸检测算法 这个pull request是会同步吗 还是说要关掉这个pull 再新开一个

2024-07-10 01:23 UTC, DefTruth commented
> > @wangzijian1010 同学，可以加我微信，后续有时间可以聊聊，微信和GitHub同名：DefTruth
> 
> 马上就加 追星成功🥹🥹 大佬就是我刚刚更新了一版本的pull request那个人脸检测算法 这个pull request是会同步吗 还是说要关掉这个pull 再新开一个

新的commit会追加到原来的PR

2024-07-10 01:31 UTC, DefTruth requested changes

2024-07-10 01:31 UTC, DefTruth commented on lite/ort/cv/yolofacev8.h
> +        float GetIoU(const lite::types::BoundingBoxType<float, float> box1, const lite::types::BoundingBoxType<float, float> box2);
统一函数命名风格为小写字母加_线，比如generate_box

2024-07-10 01:32 UTC, DefTruth commented
@wangzijian1010 这个PR问题不大了，有些代码风格需要修改一下

2024-07-10 03:04 UTC, wangzijian1010 commented
> @wangzijian1010 这个PR问题不大了，有些代码风格需要修改一下

修改完成了 大佬 @DefTruth

2024-07-10 04:25 UTC, DefTruth approved these changes
LGTM

2024-07-10 04:29 UTC, DefTruth commented
@wangzijian1010 还是有一些问题，我直接修改了。
- 1. 不推荐使用全局的using namespace std等
- 2. example可以使用lite:utils里边的函数
- 3. conf_threshold、iou_threshold需要暴露给用户配置
- 4. bbox flag需要设置为true表示结果生效，否则lite:utils相关函数会跳过

先合了，之后再抽空看下是否需要reformat

2024-07-10 04:30 UTC, merged

2024-07-10 06:05 UTC, wangzijian1010 commented
> @wangzijian1010 还是有一些问题，我直接修改了。
> 
> * 1. 不推荐使用全局的using namespace std等
> * 2. example可以使用lite:utils里边的函数
> * 3. conf_threshold、iou_threshold需要暴露给用户配置
> * 4. bbox flag需要设置为true表示结果生效，否则lite:utils相关函数会跳过
> 
> 先合了，之后再抽空看下是否需要reformat

@DefTruth 好的捏 大佬 下次这些我都看一看