update first tensortt inference example
DefTruth/lite.ai.toolkit pull request #416
Opened 2024-07-17 09:10 UTC by wangzijian1010

2024-07-17 09:24 UTC, DefTruth commented
LGTM~

2024-07-17 09:41 UTC, DefTruth requested changes

2024-07-17 09:41 UTC, DefTruth commented on cmake/lite.ai.toolkit.cmake.in
> +include_directories(${THIRD_PARTY_PATH}/TensorRT-10.1.0.27/include)
注意代码缩进

2024-07-17 09:41 UTC, DefTruth commented on CMakeLists.txt
> +message(STATUS "    TENSORRT:    ${ENABLE_ONNXRUNTIME}  Version: ${TensorRT_Version}")
日志信息对齐，: 号对齐

2024-07-17 09:41 UTC, DefTruth commented on CMakeLists.txt
> +option(ENABLE_TEST "build test examples." ON)
测试和TRT选项默认设置为OFF

2024-07-17 09:41 UTC, DefTruth commented on cmake/tensorrt.cmake
> +set(TensorRT_DIR ${THIRD_PARTY_PATH}/TensorRT-10.1.0.27)
注意TRT配置文档要对应更新为10.1

2024-07-17 09:41 UTC, DefTruth commented on examples/lite/cv/test_lite_yolov8face.cpp
> +    lite::trt::cv::face::detection::YOLOV8Face *yolov8_face  = new lite::trt::cv::face::detection::YOLOV8Face (engine_path);
删除多余空格

2024-07-17 09:41 UTC, DefTruth commented on examples/lite/cv/test_lite_yolov8face.cpp
> +
需要delete yolov8_face

2024-07-17 09:41 UTC, DefTruth commented on lite/trt/core/Logger.h
> +#ifndef LITE_AI_TOOLKIT_LOGGER_H
这个代码文件重名为trt_logger.h，保持命名风格一致

2024-07-17 09:41 UTC, DefTruth commented on lite/trt/core/trt_defs.h
> +# define LITEORT_DEBUG 1
这里不应该是LITETRT_DEBUG吗？怎么用了ORT?

2024-07-17 09:41 UTC, DefTruth commented on lite/trt/core/trt_utils.cpp
> +
空两行即可

2024-07-17 09:41 UTC, DefTruth commented on lite/trt/cv/trt_yolofacev8.cpp
> +    cudaMemcpyAsync(buffers[0], input, input_node_dims[0] * input_node_dims[1] * input_node_dims[2] * input_node_dims[3] * sizeof(float), cudaMemcpyHostToDevice, stream);
注意长代码换行，一般不建议一行太长

2024-07-17 11:28 UTC, DefTruth requested changes

2024-07-17 11:28 UTC, DefTruth commented on docs/tensorrt/tensorrt-linux-x86_64.zh.md
>  其实还是预备环境需要完成配置,如果CUDA和cudnn配置好的话,只需要对应好TensorRT和CUDA的版本就好了,本项目配置的是CUDA11.8+TensorRT8.6.0.12版本测试是OK的
这里还有版本号没修改完

2024-07-17 11:28 UTC, DefTruth commented on cmake/tensorrt.cmake
> +set(CUDA_DIR  ${THIRD_PARTY_PATH}/cuda)
这里CUDA_DIR是假设在THIRD_PARTY_PATH下，但是lite.ai.toolkit.cmake.in写的是系统路径，有矛盾。假设cuda是需要默认配置好的，在linux系统路径/usr/local/cuda即可。

2024-07-17 11:56 UTC, wangzijian1010 commented
更改完成了大佬@DefTruth

2024-07-17 12:28 UTC, DefTruth requested changes

2024-07-17 12:28 UTC, DefTruth commented on cmake/lite.ai.toolkit.cmake.in
> +  include_directories(${THIRD_PARTY_PATH}/TensorRT-10.1.0.27/include)
这个TRT的路径也需要修改

2024-07-18 01:55 UTC, wangzijian1010 commented
大佬已经修改完成了@DefTruth

2024-07-18 06:39 UTC, DefTruth commented
LGTM

2024-07-18 06:39 UTC, DefTruth approved these changes

2024-07-18 06:39 UTC, merged