Update TensorRT BasicHandler and add yolov5 cpp file
DefTruth/lite.ai.toolkit pull request #417
Opened 2024-07-21 12:56 UTC by wangzijian1010

2024-07-21 13:01 UTC, DefTruth commented
LGTM~

2024-07-22 01:07 UTC, DefTruth requested changes

2024-07-22 01:07 UTC, DefTruth commented on lite/trt/core/trt_core.h
> +    class LITE_EXPORTS TRTYoloV5;     // [2] * reference: https://github.com/derronqi/yolov8-face
这里reference的链接不对，需要是yolov5的

2024-07-22 01:07 UTC, DefTruth commented on lite/trt/cv/trt_yolov5.cpp
> +    float* output = new float[pred_dims[0] * pred_dims[1] * pred_dims[2]];
函数内new的内存没有释放

2024-07-22 01:07 UTC, DefTruth commented on lite/trt/cv/trt_yolov5.cpp
> +// Created by root on 7/20/24.
author改成提交者的名字

2024-07-22 01:07 UTC, DefTruth commented on lite/trt/cv/trt_yolofacev8.cpp
> +    float* output = new float[output_node_dims[0][0] * output_node_dims[0][1] * output_node_dims[0][2]];
注意检查函数内new的内存是否释放

2024-07-22 01:07 UTC, DefTruth commented on examples/lite/cv/test_lite_yolov5.cpp
> +  std::string save_img_path = "../../../examples/logs/test_lite_yolov5_1647_onnx.jpg";
这里为什么改了默认的保存名称？建议使用默认值

2024-07-22 01:07 UTC, DefTruth commented on examples/lite/cv/test_lite_yolov5.cpp
> +    std::string save_img_path = "../../../examples/logs/test_lite_yolov5_1647.jpg";
保存的测试图片名称可以改成：test_lite_yolov5_xx_trt.jpg，其余框架的测试类似，xx为可选，比如test_lite_yolov5_5_trt.jpg

2024-07-22 03:47 UTC, wangzijian1010 commented
修改完成了大佬@DefTruth

2024-07-22 04:20 UTC, DefTruth requested changes

2024-07-22 04:20 UTC, DefTruth commented on lite/trt/cv/trt_yolov5.cpp
> +    float* output = new float[pred_dims[0] * pred_dims[1] * pred_dims[2]];
这里的内存依然没有合理释放

2024-07-22 04:55 UTC, wangzijian1010 commented on lite/trt/cv/trt_yolov5.cpp
> +    float* output = new float[pred_dims[0] * pred_dims[1] * pred_dims[2]];
改到yolov8face那个文件上去了 哈哈哈@DefTruth

2024-07-22 04:59 UTC, DefTruth approved these changes

2024-07-22 05:03 UTC, merged