[TensorRT] [OnnxRuntime] support Stable Diffusion text2image PipeLine code
DefTruth/lite.ai.toolkit pull request #432
Opened 2024-09-01 08:18 UTC by wangzijian1010

2024-09-02 01:30 UTC, DefTruth commented
LGTM

2024-09-02 01:41 UTC, DefTruth requested changes

2024-09-02 01:41 UTC, DefTruth commented on cmake/utils.cmake
> +        set(LITE_DEPENDENCIES ${LITE_DEPENDENCIES} onnxruntime libddim_scheduler_cpp.so)
这里应该只写`ddim_scheduler_cpp`就可以链接到

2024-09-02 01:41 UTC, DefTruth commented on cmake/utils.cmake
> +        set(LITE_DEPENDENCIES ${LITE_DEPENDENCIES}  cudart nvinfer nvonnxparser nvinfer_plugin libddim_scheduler_cpp.so)
同上

2024-09-02 01:41 UTC, DefTruth commented on examples/lite/sd/test_lite_clip.cpp
> +    std::string onnx_path = "/home/wangzijian/lite.ai.toolkit/examples/hub/onnx/sd/clip_model.onnx";
路径写成相对路径

2024-09-02 01:41 UTC, DefTruth commented on examples/lite/sd/test_lite_clip.cpp
> +    auto scheduler = Scheduler::DDIMScheduler("/home/wangzijian/lite.ai.toolkit/lite/ort/sd/scheduler_config.json");
路径写成相对路径

2024-09-02 01:41 UTC, DefTruth commented on examples/lite/sd/test_lite_clip.cpp
> +    std::string engine_path = "/home/wangzijian/lite.ai.toolkit/examples/hub/trt/clip_text_model_fp16.engine";
路径写成相对路径

2024-09-02 01:41 UTC, DefTruth commented on examples/lite/sd/test_lite_clip.cpp
> +//    test_lite();
为什么要注释掉这句？这样main函数是空函数

2024-09-02 01:41 UTC, DefTruth commented on examples/lite/sd/test_lite_sd_pipeline.cpp
> +}
缺少return 0

2024-09-02 01:41 UTC, DefTruth commented on examples/lite/sd/test_lite_unet.cpp
> +    std::string engine_path = "/home/wangzijian/lite.ai.toolkit/examples/hub/onnx/sd/unet_model.onnx";
写相对路径

2024-09-02 01:41 UTC, DefTruth commented on examples/lite/sd/test_lite_unet.cpp
> +    std::string engine_path = "/home/wangzijian/lite.ai.toolkit/examples/hub/trt/unet_fp16.engine";
写相对路径

2024-09-02 01:41 UTC, DefTruth commented on examples/lite/sd/test_lite_vae.cpp
> +    std::string engine_path = "/home/wangzijian/lite.ai.toolkit/examples/hub/onnx/sd/vae_model.onnx";
写相对路径

2024-09-02 01:41 UTC, DefTruth commented on examples/lite/sd/test_lite_vae.cpp
> +    std::string engine_path = "/home/wangzijian/lite.ai.toolkit/examples/hub/trt/vae_model_fp16.engine";
写相对路径

2024-09-02 01:41 UTC, DefTruth commented on lite/ort/sd/unet.cpp
> +    auto scheduler = Scheduler::DDIMScheduler("/home/wangzijian/lite.ai.toolkit/lite/ort/sd/scheduler_config.json");
这里应该支持传一个路径参数进来，而非写死

2024-09-02 01:41 UTC, DefTruth commented on lite/trt/sd/trt_pipeline.cpp
> +    std::vector<std::vector<float>> clip_output;
这里逻辑有点问题，每次infer加载的是绝对路径的模型，应该在构造函数中初始化clip/unet/vae

2024-09-02 01:41 UTC, DefTruth commented on lite/trt/sd/trt_unet.cpp
> +                   [](half h) { return __half2float(h); });
这里有优化空间，之后可以考虑写成cuda kernel

2024-09-02 01:41 UTC, DefTruth commented on lite/trt/sd/trt_vae.cpp
> +    std::string filename = "/home/wangzijian/lite.ai.toolkit/trt_final_latent_data.bin";
注意这些模型路径问题

2024-09-02 01:46 UTC, wangzijian1010 commented on lite/trt/sd/trt_unet.cpp
> +                   [](half h) { return __half2float(h); });
我一开始还写的for循环 嘻嘻嘻 怪不得慢

2024-09-02 01:53 UTC, wangzijian1010 commented on lite/trt/sd/trt_pipeline.cpp
> +    std::vector<std::vector<float>> clip_output;
这个地方主要是我电脑显存不够 我在构造函数里面加载3个模型 电脑就死机了

2024-09-02 03:12 UTC, DefTruth commented on lite/trt/sd/trt_pipeline.cpp
> +    std::vector<std::vector<float>> clip_output;
可以在构造函数加delay_init的选项，默认为false。当为true时，在inference阶段online初始化模型。为false时，在构造函数初始化模型。

2024-09-02 11:53 UTC, wangzijian1010 commented on examples/lite/sd/test_lite_clip.cpp
> +    auto scheduler = Scheduler::DDIMScheduler("/home/wangzijian/lite.ai.toolkit/lite/ort/sd/scheduler_config.json");
归入pipeline

2024-09-03 09:57 UTC, DefTruth requested changes

2024-09-03 09:57 UTC, DefTruth commented on lite/trt/sd/trt_unet.cpp
> +    std::cout << "没有加载engine的耗时是: " << duration << " 毫秒" << std::endl;
这句日志需要用LITETRT_DEBUG宏限制住

2024-09-03 09:57 UTC, DefTruth commented on lite/trt/sd/trt_pipeline.cpp
> +    // 初始时不分配资源，将成员变量置为 nullptr
这里比较建议这样处理：
```C++
// 声明
TRTPipeline::TRTPipeline(const std::string &_clip_engine_path, const std::string &_unet_engine_path,
                         const std::string &_vae_engine_path, bool _delay_init = true);
TRTPipeline::TRTPipeline(const std::string &_clip_engine_path, const std::string &_unet_engine_path,
                         const std::string &_vae_engine_path, bool _delay_init):
         clip_engine_path(_clip_engine_path),
          unet_engine_path(_unet_engine_path),
          vae_engine_path(_vae_engine_path),  delay_init(_delay_init){
    // 默认delay_init为true, 初始时不分配资源，将成员变量置为 nullptr
    if (!delay_init) {
        clip = std::make_unique<TRTClip>(clip_engine_path);
        // ...
    }
}
```

2024-09-03 09:57 UTC, DefTruth commented on lite/trt/sd/trt_pipeline.cpp
> +    clip.reset(); // 使用后立即释放
// 建议在delay_init模式下支持低显存情形，vae/unet类似
if (delay_init) {
  clip.reset();
}

2024-09-04 03:52 UTC, DefTruth requested changes

2024-09-04 03:52 UTC, DefTruth commented on lite/ort/sd/pipeline.cpp
> +    // 这里的prompt是一个vector [0] 代表
这个函数为什么是空的？没有实现？

2024-09-04 05:07 UTC, DefTruth approved these changes

2024-09-04 05:08 UTC, merged